name: Build wheels

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch: {}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel
      - name: Build wheels
        working-directory: python
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "pp* *-musllinux_*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: python/wheelhouse/*

